export type Role='viewer'|'student'|'instructor'|'admin'
export interface User{ id:string; full_name:string; role:Role; active:boolean }
export interface Location{ id:string; code:string; standard_code?:string; name:string; type:string; country?:string; region?:string; city?:string; address?:string; lat:number; lng:number; time_zone?:string; status?:string; data_source?:string; owner_id?:string; approval_status?:string }
export interface Link{ id:string; code:string; name:string; from_id:string; to_id:string; mode:string; distance_km:number; transit_hours:number; carrier?:string; reliability:number; active?:boolean; data_source?:string; owner_id?:string; approval_status?:string }
export interface Rate{ id:string; code:string; name:string; link_id:string; carrier?:string; equipment_id:string; rate:number; currency:string; basis:string; fuel_pct:number; surcharge:number; surcharge_basis?:string; valid_from?:string; valid_to?:string; active?:boolean; data_source?:string; owner_id?:string; approval_status?:string }
export interface Equipment{ id:string; name:string; category:string; teu:number; capacity_kg?:number; capacity_m3?:number; status?:string }
export interface RouteResult{path:string[];legs:any[];transport:number;services:any;insurance:number;total:number;hours:number;distance_km:number;transfers:number;reliability:number;co2_kg:number;missing_rates:number;completeness:number;score:number}
export interface ServiceRule{ id:string; name:string; category:string; context:string; node_type:string; transition:string; requirement:string; basis:string; default_rate:number; currency:string; cargo:string; equipment_category:string; trade_scope:string; reason?:string }
export interface SavedRoute{ id:string; code:string; name:string; owner_id?:string; visibility:string; payload:any; updated_at:string }
export interface DataStats{ locations:number; links:number; rates:number; equipment:number; services:number; saved_routes:number; pending_locations:number; pending_links:number; pending_rates:number }
