import {useEffect,useState} from 'react';
import {api} from '../api';
import type {Location,Link,Rate,Equipment,SavedRoute} from '../types';
import {useAuth} from '../context/AuthContext';

type Tab='locations'|'links'|'rates'|'equipment'|'validation'|'routes';
type DialogKind='location'|'link'|'rate'|'equipment'|'route';
const BASES=['SHIPMENT','KG','TON','M3','REVENUE_TON','KM','TON_KM','CONTAINER','TEU','FEU','PALLET','DAY','HOUR'];
const MODES=['road','rail','sea','air','inland'];
const LOCATION_TYPES=['factory','warehouse','customer','seaport','inland_port','airport','rail_terminal','road_terminal','icd','logistics_center','border_gate','distribution_center'];

export default function MasterData(){
 const {user}=useAuth();
 const [tab,setTab]=useState<Tab>('locations'),[locations,setLocations]=useState<Location[]>([]),[links,setLinks]=useState<Link[]>([]),[rates,setRates]=useState<Rate[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[routes,setRoutes]=useState<SavedRoute[]>([]),[validation,setValidation]=useState<any>(null),[q,setQ]=useState(''),[source,setSource]=useState('all'),[dialog,setDialog]=useState<{kind:DialogKind;record?:any}|null>(null),[form,setForm]=useState<any>({}),[msg,setMsg]=useState(''),[dialogMsg,setDialogMsg]=useState(''),[saving,setSaving]=useState(false);
 const reload=()=>Promise.all([api<Location[]>('/api/master/locations'),api<Link[]>('/api/master/links'),api<Rate[]>('/api/master/rates'),api<Equipment[]>('/api/master/equipment'),api<SavedRoute[]>('/api/saved-routes'),api<any>('/api/master/validation')]).then(([a,b,c,d,e,v])=>{setLocations(a);setLinks(b);setRates(c);setEquipment(d);setRoutes(e);setValidation(v)}).catch((e:any)=>setMsg(e.message));
 useEffect(()=>{reload()},[]);
 const qq=q.toLowerCase();
 const sf=(x:any)=>source==='all'||(source==='master'&&(x.data_source||'MASTER')==='MASTER')||(source==='pending'&&(x.approval_status==='PENDING'||x.data_source==='STUDENT-PENDING'))||(source==='approved'&&x.data_source==='STUDENT-APPROVED');
 const role=String(user.role||'').trim().toLowerCase();
 const normalizedRole=role==='staff'?'student':role==='manager'?'instructor':role;
 const sameId=(a:any,b:any)=>String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase();
 const canStudentOwn=(x:any)=>normalizedRole==='student'&&sameId(x.owner_id,user.id)&&String(x.approval_status||'').toUpperCase()==='PENDING';
 const canEdit=(x:any)=>['admin','instructor'].includes(normalizedRole)||canStudentOwn(x);
 const canDelete=(x:any)=>['admin','instructor'].includes(normalizedRole)||canStudentOwn(x);
 const canApprove=(x:any)=>['admin','instructor'].includes(normalizedRole)&&String(x.approval_status||'').toUpperCase()==='PENDING';
 const canAddLlr=normalizedRole!=='viewer';
 const canClone=normalizedRole!=='viewer';
 const canManageReference=['admin','instructor'].includes(normalizedRole);
 const canDeleteEquipment=normalizedRole==='admin';
 const canEditRoute=(x:SavedRoute)=>['admin','instructor'].includes(user.role)||x.owner_id===user.id;

 function open(kind:DialogKind,record?:any){
  setMsg('');setDialogMsg('');setDialog({kind,record});
  if(kind==='location')setForm(record?{...record}:{code:'',standard_code:'',name:'',type:'seaport',country:'',region:'',city:'',address:'',lat:0,lng:0,time_zone:'',status:'active'});
  if(kind==='link')setForm(record?{...record}:{code:'',name:'',from_id:locations[0]?.id||'',to_id:locations[1]?.id||'',mode:'road',distance_km:0,transit_hours:0,carrier:'',reliability:90,active:true});
  if(kind==='rate')setForm(record?{...record}:{code:'',name:'',link_id:links[0]?.id||'',carrier:'',equipment_id:'ANY',rate:0,currency:'USD',basis:'SHIPMENT',fuel_pct:0,surcharge:0,surcharge_basis:'SHIPMENT',valid_from:'',valid_to:'',active:true});
  if(kind==='equipment')setForm(record?{...record}:{id:'',name:'',category:'container',teu:0,capacity_kg:0,capacity_m3:0,status:'active'});
  if(kind==='route')setForm(record?{...record,payload_text:JSON.stringify(record.payload||{},null,2)}:{code:'',name:'',visibility:'personal',payload_text:'{}'});
 }
 function uniqueCopyCode(base:string,existing:string[]){
  const clean=(base||'COPY').trim()||'COPY';
  let candidate=`${clean}-COPY`,n=2;
  const used=new Set(existing.map(x=>String(x||'').trim().toLowerCase()));
  while(used.has(candidate.toLowerCase()))candidate=`${clean}-COPY-${n++}`;
  return candidate;
 }
 function duplicateLink(x:Link){
  setMsg('');setDialogMsg('');setDialog({kind:'link'});
  const {id,data_source,owner_id,approval_status,...rest}=x as any;
  setForm({...rest,code:uniqueCopyCode(x.code,links.map(z=>z.code)),name:`${x.name||x.code} Copy`});
 }
 function duplicateRate(x:Rate){
  setMsg('');setDialogMsg('');setDialog({kind:'rate'});
  const {id,data_source,owner_id,approval_status,...rest}=x as any;
  setForm({...rest,code:uniqueCopyCode(x.code,rates.map(z=>z.code)),name:`${x.name||x.code} Copy`});
 }
 async function reverseLink(x:Link){
  const ok=confirm(`Create reverse Transport Link for ${x.code}? Attached visible Rate Cards will also be copied to the reverse direction for review.`);
  if(!ok)return;
  try{
   const r=await api<any>(`/api/master/links/${x.id}/reverse`,{method:'POST'});
   setMsg(`Created reverse link ${r.link?.code||''} and copied ${r.copied_rates??0} Rate Card(s). Verify directional rates before production use.`);
   await reload();
  }catch(e:any){setMsg(e.message||String(e))}
 }
 async function saveDialog(){if(!dialog||saving)return;setDialogMsg('');
  try{
   const edit=!!dialog.record;let path='',body:any={...form};
   const code=String(form.code||'').trim(); const name=String(form.name||'').trim();
   if(dialog.kind!=='equipment'&&dialog.kind!=='route'&&(!code||!name)){setDialogMsg('Code and Name are required.');return}
   if(!edit&&dialog.kind==='location'&&locations.some(x=>String(x.code).trim().toLowerCase()===code.toLowerCase())){setDialogMsg(`Location code ${code} already exists. Close this dialog and use Edit on your own Pending record instead.`);return}
   if(!edit&&dialog.kind==='link'&&links.some(x=>String(x.code).trim().toLowerCase()===code.toLowerCase())){setDialogMsg(`Transport Link code ${code} already exists. Use Edit on the existing record or choose a new code.`);return}
   if(!edit&&dialog.kind==='rate'&&rates.some(x=>String(x.code).trim().toLowerCase()===code.toLowerCase())){setDialogMsg(`Rate Card code ${code} already exists. Use Edit on the existing record or choose a new code.`);return}
   if(dialog.kind==='location'){path='/api/master/locations'+(edit?`/${dialog.record.id}`:'');delete body.id;delete body.data_source;delete body.owner_id;delete body.approval_status;delete body.approved_by;delete body.approved_at;}
   if(dialog.kind==='link'){path='/api/master/links'+(edit?`/${dialog.record.id}`:'');delete body.id;delete body.data_source;delete body.owner_id;delete body.approval_status;delete body.approved_by;delete body.approved_at;}
   if(dialog.kind==='rate'){path='/api/master/rates'+(edit?`/${dialog.record.id}`:'');delete body.id;delete body.data_source;delete body.owner_id;delete body.approval_status;delete body.approved_by;delete body.approved_at;body.rate=+body.rate;body.fuel_pct=+body.fuel_pct;body.surcharge=+body.surcharge;body.valid_from=body.valid_from||null;body.valid_to=body.valid_to||null;}
   if(dialog.kind==='equipment'){path='/api/master/equipment'+(edit?`/${dialog.record.id}`:'');body.teu=+body.teu;body.capacity_kg=+body.capacity_kg;body.capacity_m3=+body.capacity_m3;}
   if(dialog.kind==='route'){path='/api/saved-routes'+(edit?`/${dialog.record.id}`:'');body={code:form.code,name:form.name,visibility:form.visibility,payload:JSON.parse(form.payload_text||'{}')};}
   setSaving(true); await api(path,{method:edit?'PUT':'POST',body:JSON.stringify(body)}); setDialog(null);setMsg(`${edit?'Updated':'Added'} ${dialog.kind} successfully.`);await reload();
  }catch(e:any){setDialogMsg(e.message||String(e))}finally{setSaving(false)} }
 async function remove(kind:'locations'|'links'|'rates'|'equipment'|'route',id:string){if(!confirm(`Delete ${kind.slice(0,-1)} ${id}?`))return;try{const path=kind==='route'?`/api/saved-routes/${id}`:`/api/master/${kind}/${id}`;await api(path,{method:'DELETE'});setMsg(`Deleted ${id}.`);await reload()}catch(e:any){setMsg(e.message)}}
 async function approveRecord(recordType:'location'|'link'|'rate',id:string){try{await api('/api/contributions/approve',{method:'POST',body:JSON.stringify({record_type:recordType,record_id:id})});setMsg(`Approved ${id} into Master Data.`);await reload()}catch(e:any){setMsg(e.message)}}
 async function runValidation(){try{setValidation(await api<any>('/api/master/validation'));setMsg('Network validation refreshed.')}catch(e:any){setMsg(e.message)}}
 const addButton=tab==='locations'&&canAddLlr?<button className="primary compact" onClick={()=>open('location')}>+ Add Location</button>:tab==='links'&&canAddLlr?<button className="primary compact" onClick={()=>open('link')}>+ Add Transport Link</button>:tab==='rates'&&canAddLlr?<button className="primary compact" onClick={()=>open('rate')}>+ Add Rate Card</button>:tab==='equipment'&&canManageReference?<button className="primary compact" onClick={()=>open('equipment')}>+ Add Equipment</button>:tab==='routes'?<button className="primary compact" onClick={()=>open('route')}>+ Add Saved Route</button>:tab==='validation'?<button className="primary compact" onClick={runValidation}>↻ Run Validation</button>:null;
 return <>
  <div className="page-head"><div><h2>Master Data & Network</h2><p>Shared server database with server-enforced CRUD permissions and Student Pending → Approval workflow.</p></div><span className="pill">{locations.length} LOC · {links.length} LINKS · {rates.length} RATES</span></div>
  <div className="policy-banner"><b>Access:</b> {normalizedRole==='student'?<> You may Add records and Edit/Delete only records marked <b>STUDENT-PENDING · {user.id}</b>. You may also <b>Duplicate</b> visible Links/Rate Cards and <b>Reverse</b> an approved or own-pending Link; the new records become your Pending data. Approval is performed by Instructor/Admin.</>:['admin','instructor'].includes(normalizedRole)?<> Pending student records show <b>Edit · Approve · Delete</b>. Transport Links also provide <b>Reverse · Duplicate</b>; Rate Cards provide <b>Duplicate</b>. Approve in dependency order: Location → Transport Link → Rate Card.</>:<> Master Data is read-only for Viewer.</>}</div>
  <div className="tabs">{([['locations','Locations'],['links','Transport Links'],['rates','Rate Cards'],['equipment','Equipment'],['validation','Network Validation'],['routes','Saved Routes']] as any[]).map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setQ('')}}>{l}</button>)}</div>
  <section className="card"><div className="card-toolbar"><div className="toolbar grow">{['locations','links','rates'].includes(tab)&&<><input placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)}/><select className="filter-select" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All Data Sources</option><option value="master">Master Original</option><option value="pending">Student Pending</option><option value="approved">Student Approved</option></select></>}</div>{addButton}</div>
  {tab==='locations'&&<div className="table-scroll"><table><thead><tr><th>Code</th><th>Standard ID</th><th>Name</th><th>Type</th><th>Country / City</th><th>Coordinates</th><th>Data Source</th><th>Actions</th></tr></thead><tbody>{locations.filter(x=>sf(x)&&(x.code+x.name+x.type+(x.country||'')).toLowerCase().includes(qq)).map(x=><tr key={x.id} className={x.approval_status==='PENDING'?'pending-row':''}><td><b>{x.code}</b></td><td>{x.standard_code||'—'}</td><td>{x.name}</td><td>{x.type}</td><td>{x.country} / {x.city}</td><td>{Number(x.lat).toFixed(4)}, {Number(x.lng).toFixed(4)}</td><td><DataBadge x={x}/></td><td><Actions edit={canEdit(x)?()=>open('location',x):undefined} approve={canApprove(x)?()=>approveRecord('location',x.id):undefined} del={canDelete(x)?()=>remove('locations',x.id):undefined}/></td></tr>)}</tbody></table></div>}
  {tab==='links'&&<div className="table-scroll"><table><thead><tr><th>Code</th><th>Name</th><th>From → To</th><th>Mode</th><th>Carrier</th><th>Distance</th><th>Transit</th><th>Reliability</th><th>Source</th><th>Actions</th></tr></thead><tbody>{links.filter(x=>sf(x)&&(x.code+x.name+x.mode+(x.carrier||'')).toLowerCase().includes(qq)).map(x=><tr key={x.id} className={x.approval_status==='PENDING'?'pending-row':''}><td><b>{x.code}</b></td><td>{x.name}</td><td>{x.from_id} → {x.to_id}</td><td>{x.mode}</td><td>{x.carrier}</td><td>{x.distance_km} km</td><td>{x.transit_hours} h</td><td>{x.reliability}%</td><td><DataBadge x={x}/></td><td><Actions edit={canEdit(x)?()=>open('link',x):undefined} reverse={canClone?()=>reverseLink(x):undefined} duplicate={canClone?()=>duplicateLink(x):undefined} approve={canApprove(x)?()=>approveRecord('link',x.id):undefined} del={canDelete(x)?()=>remove('links',x.id):undefined}/></td></tr>)}</tbody></table></div>}
  {tab==='rates'&&<div className="table-scroll"><table><thead><tr><th>Code</th><th>Name</th><th>Link</th><th>Carrier</th><th>Equipment</th><th>Rate</th><th>Basis</th><th>Fuel</th><th>Surcharge</th><th>Validity</th><th>Source</th><th>Actions</th></tr></thead><tbody>{rates.filter(x=>sf(x)&&(x.code+x.name+(x.carrier||'')+x.equipment_id).toLowerCase().includes(qq)).map(x=><tr key={x.id} className={x.approval_status==='PENDING'?'pending-row':''}><td><b>{x.code}</b></td><td>{x.name}</td><td>{x.link_id}</td><td>{x.carrier}</td><td>{x.equipment_id}</td><td>{x.rate} {x.currency}</td><td>{x.basis}</td><td>{x.fuel_pct}%</td><td>{x.surcharge}</td><td>{x.valid_from||'—'} → {x.valid_to||'—'}</td><td><DataBadge x={x}/></td><td><Actions edit={canEdit(x)?()=>open('rate',x):undefined} duplicate={canClone?()=>duplicateRate(x):undefined} approve={canApprove(x)?()=>approveRecord('rate',x.id):undefined} del={canDelete(x)?()=>remove('rates',x.id):undefined}/></td></tr>)}</tbody></table></div>}
  {tab==='equipment'&&<div className="table-scroll"><table><thead><tr><th>ID</th><th>Name</th><th>Category</th><th>TEU</th><th>Capacity kg</th><th>Capacity m³</th><th>Status</th><th>Actions</th></tr></thead><tbody>{equipment.map(x=><tr key={x.id}><td><b>{x.id}</b></td><td>{x.name}</td><td>{x.category}</td><td>{x.teu}</td><td>{x.capacity_kg||0}</td><td>{x.capacity_m3||0}</td><td>{x.status||'active'}</td><td><Actions edit={canManageReference?()=>open('equipment',x):undefined} del={canDeleteEquipment&&x.id!=='ANY'?()=>remove('equipment',x.id):undefined}/></td></tr>)}</tbody></table></div>}
  {tab==='validation'&&validation&&<><div className="kpis"><K l="Locations" v={validation.locations}/><K l="Links" v={validation.links}/><K l="Rates" v={validation.rates}/><K l="Errors" v={validation.errors}/><K l="Warnings" v={validation.warnings}/></div><p className="note">Validation is a computed audit view, so rows are intentionally not editable/deletable. Use Edit/Delete in the source data tabs above.</p><div className="table-scroll"><table><thead><tr><th>Severity</th><th>Object</th><th>Issue</th><th>Recommendation</th></tr></thead><tbody>{validation.issues.map((x:any,i:number)=><tr key={i}><td><span className={'source '+x.severity}>{x.severity}</span></td><td>{x.object}</td><td>{x.issue}</td><td>{x.recommendation}</td></tr>)}</tbody></table></div></>}
  {tab==='routes'&&<div className="table-scroll"><table><thead><tr><th>Code</th><th>Name</th><th>Owner</th><th>Visibility</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{routes.map(x=><tr key={x.id}><td><b>{x.code}</b></td><td>{x.name}</td><td>{x.owner_id}</td><td>{x.visibility}</td><td>{x.updated_at}</td><td><Actions edit={canEditRoute(x)?()=>open('route',x):undefined} del={canEditRoute(x)?()=>remove('route',x.id):undefined}/></td></tr>)}</tbody></table></div>}
  </section>{msg&&<div className="status">{msg}</div>}
  <p className="footnote">Permissions: Student = Add + Edit/Delete own Pending Location/Link/Rate and may Duplicate visible Link/Rate or create a Reverse Link as own Pending data; Instructor/Admin may Edit / Approve / Delete and use Duplicate/Reverse directly in Master Data. Reverse Link copies attached visible Rate Cards for review; directional freight rates must be verified. Equipment/Service reference data require Instructor/Admin; destructive deletes are still validated by the backend.</p>
  {dialog&&<CrudModal title={`${dialog.record?'Edit':'Add'} ${dialog.kind}`} onClose={()=>{setDialog(null);setDialogMsg('')}} onSave={saveDialog} error={dialogMsg} saving={saving} editing={!!dialog.record}>{dialog.kind==='location'&&<LocationForm f={form} setF={setForm}/>} {dialog.kind==='link'&&<LinkForm f={form} setF={setForm} locations={locations}/>} {dialog.kind==='rate'&&<RateForm f={form} setF={setForm} links={links} equipment={equipment}/>} {dialog.kind==='equipment'&&<EquipmentForm f={form} setF={setForm} editing={!!dialog.record}/>} {dialog.kind==='route'&&<RouteForm f={form} setF={setForm}/>}</CrudModal>}
 </>;
}
function DataBadge({x}:{x:any}){const text=x.approval_status==='PENDING'?'STUDENT-PENDING':x.data_source||'MASTER';return <span className={'source '+(x.approval_status==='PENDING'?'warning':'')}>{text}{x.owner_id?` · ${x.owner_id}`:''}</span>}
function Actions({edit,reverse,duplicate,approve,del}:{edit?:()=>void;reverse?:()=>void;duplicate?:()=>void;approve?:()=>void;del?:()=>void}){return <div className="table-actions">{edit&&<button className="small-btn" onClick={edit}>Edit</button>}{reverse&&<button className="small-btn reverse-lite" onClick={reverse}>Reverse</button>}{duplicate&&<button className="small-btn" onClick={duplicate}>Duplicate</button>}{approve&&<button className="small-btn success-lite" onClick={approve}>Approve</button>}{del&&<button className="small-btn danger" onClick={del}>Delete</button>}{!edit&&!reverse&&!duplicate&&!approve&&!del&&<span className="note">Read only</span>}</div>}
function CrudModal({title,onClose,onSave,children,error,saving,editing}:{title:string;onClose:()=>void;onSave:()=>void;children:any;error?:string;saving?:boolean;editing?:boolean}){return <div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)onClose()}}><div className="modal-card"><div className="modal-head"><h3>{title}</h3><button className="x" disabled={saving} onClick={onClose}>×</button></div><div className="modal-body">{children}{error&&<div className="modal-error"><b>Cannot save:</b> {error}</div>}<div className="modal-actions"><button disabled={saving} onClick={onClose}>Cancel</button><button className="primary" disabled={saving} onClick={onSave}>{saving?'Saving…':editing?'Save Changes':'Add Record'}</button></div></div></div></div>}
const F=({label,children}:{label:string;children:any})=><label className="field"><span>{label}</span>{children}</label>;
function LocationForm({f,setF}:{f:any;setF:any}){return <><div className="form-grid three"><F label="Internal Code *"><input value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/></F><F label="Standard ID"><input value={f.standard_code||''} onChange={e=>setF({...f,standard_code:e.target.value})}/></F><F label="Type"><select value={f.type||'seaport'} onChange={e=>setF({...f,type:e.target.value})}>{LOCATION_TYPES.map(x=><option key={x}>{x}</option>)}</select></F></div><F label="Name *"><input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></F><div className="form-grid three"><F label="Country"><input value={f.country||''} onChange={e=>setF({...f,country:e.target.value})}/></F><F label="Region"><input value={f.region||''} onChange={e=>setF({...f,region:e.target.value})}/></F><F label="City"><input value={f.city||''} onChange={e=>setF({...f,city:e.target.value})}/></F></div><F label="Address"><input value={f.address||''} onChange={e=>setF({...f,address:e.target.value})}/></F><div className="form-grid three"><F label="Latitude *"><input type="number" step="any" value={f.lat??0} onChange={e=>setF({...f,lat:+e.target.value})}/></F><F label="Longitude *"><input type="number" step="any" value={f.lng??0} onChange={e=>setF({...f,lng:+e.target.value})}/></F><F label="Time Zone"><input value={f.time_zone||''} onChange={e=>setF({...f,time_zone:e.target.value})}/></F></div><F label="Status"><select value={f.status||'active'} onChange={e=>setF({...f,status:e.target.value})}><option value="active">active</option><option value="inactive">inactive</option></select></F></>}
function LinkForm({f,setF,locations}:{f:any;setF:any;locations:Location[]}){return <><div className="form-grid two"><F label="Link Code *"><input value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/></F><F label="Link Name *"><input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></F></div><div className="form-grid three"><F label="Mode"><select value={f.mode||'road'} onChange={e=>setF({...f,mode:e.target.value})}>{MODES.map(x=><option key={x} value={x}>{x}</option>)}</select></F><F label="From *"><select value={f.from_id||''} onChange={e=>setF({...f,from_id:e.target.value})}>{locations.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></F><F label="To *"><select value={f.to_id||''} onChange={e=>setF({...f,to_id:e.target.value})}>{locations.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></F></div><div className="form-grid three"><F label="Distance (km)"><input type="number" value={f.distance_km??0} onChange={e=>setF({...f,distance_km:+e.target.value})}/></F><F label="Transit (hours)"><input type="number" value={f.transit_hours??0} onChange={e=>setF({...f,transit_hours:+e.target.value})}/></F><F label="Reliability (%)"><input type="number" value={f.reliability??90} onChange={e=>setF({...f,reliability:+e.target.value})}/></F></div><F label="Carrier / Provider"><input value={f.carrier||''} onChange={e=>setF({...f,carrier:e.target.value})}/></F><label className="check-line"><input type="checkbox" checked={f.active!==false} onChange={e=>setF({...f,active:e.target.checked})}/> Active Link</label></>}
function RateForm({f,setF,links,equipment}:{f:any;setF:any;links:Link[];equipment:Equipment[]}){return <><F label="Transport Link *"><select value={f.link_id||''} onChange={e=>setF({...f,link_id:e.target.value})}>{links.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></F><div className="form-grid two"><F label="Rate Code *"><input value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/></F><F label="Rate Name *"><input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></F></div><div className="form-grid three"><F label="Carrier"><input value={f.carrier||''} onChange={e=>setF({...f,carrier:e.target.value})}/></F><F label="Equipment"><select value={f.equipment_id||'ANY'} onChange={e=>setF({...f,equipment_id:e.target.value})}>{equipment.map(x=><option key={x.id} value={x.id}>{x.id} — {x.name}</option>)}</select></F><F label="Currency"><input value={f.currency||'USD'} onChange={e=>setF({...f,currency:e.target.value.toUpperCase()})}/></F></div><div className="form-grid three"><F label="Freight Rate"><input type="number" step="any" value={f.rate??0} onChange={e=>setF({...f,rate:+e.target.value})}/></F><F label="Basis"><select value={f.basis||'SHIPMENT'} onChange={e=>setF({...f,basis:e.target.value})}>{BASES.map(x=><option key={x}>{x}</option>)}</select></F><F label="Fuel surcharge (%)"><input type="number" step="any" value={f.fuel_pct??0} onChange={e=>setF({...f,fuel_pct:+e.target.value})}/></F></div><div className="form-grid three"><F label="Fixed surcharge"><input type="number" step="any" value={f.surcharge??0} onChange={e=>setF({...f,surcharge:+e.target.value})}/></F><F label="Surcharge basis"><select value={f.surcharge_basis||'SHIPMENT'} onChange={e=>setF({...f,surcharge_basis:e.target.value})}>{BASES.map(x=><option key={x}>{x}</option>)}</select></F><F label="Active"><select value={String(f.active!==false)} onChange={e=>setF({...f,active:e.target.value==='true'})}><option value="true">active</option><option value="false">inactive</option></select></F></div><div className="form-grid two"><F label="Valid From"><input type="date" value={f.valid_from||''} onChange={e=>setF({...f,valid_from:e.target.value})}/></F><F label="Valid To"><input type="date" value={f.valid_to||''} onChange={e=>setF({...f,valid_to:e.target.value})}/></F></div></>}
function EquipmentForm({f,setF,editing}:{f:any;setF:any;editing:boolean}){return <><div className="form-grid two"><F label="Equipment ID *"><input disabled={editing} value={f.id||''} onChange={e=>setF({...f,id:e.target.value.toUpperCase()})}/></F><F label="Name *"><input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></F></div><div className="form-grid three"><F label="Category"><input value={f.category||''} onChange={e=>setF({...f,category:e.target.value})}/></F><F label="TEU"><input type="number" step="0.1" value={f.teu??0} onChange={e=>setF({...f,teu:+e.target.value})}/></F><F label="Status"><select value={f.status||'active'} onChange={e=>setF({...f,status:e.target.value})}><option>active</option><option>inactive</option></select></F></div><div className="form-grid two"><F label="Capacity kg"><input type="number" value={f.capacity_kg??0} onChange={e=>setF({...f,capacity_kg:+e.target.value})}/></F><F label="Capacity m³"><input type="number" step="0.1" value={f.capacity_m3??0} onChange={e=>setF({...f,capacity_m3:+e.target.value})}/></F></div></>}
function RouteForm({f,setF}:{f:any;setF:any}){return <><div className="form-grid two"><F label="Route Code *"><input value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/></F><F label="Route Name *"><input value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></F></div><F label="Visibility"><select value={f.visibility||'personal'} onChange={e=>setF({...f,visibility:e.target.value})}><option value="personal">personal</option><option value="shared">shared</option></select></F><F label="Route payload JSON"><textarea rows={10} value={f.payload_text||'{}'} onChange={e=>setF({...f,payload_text:e.target.value})}/></F></>}
function K({l,v}:{l:string,v:number}){return <div className="kpi"><small>{l}</small><b>{v}</b></div>}
